// 01_Studi/04_Front_End/09_Develop_Web_App_React.js/20_Open_Another_Framework_Vue.js/03_Vue.js_Details/01_Example_Lesson/06_example/src/components/CounterComponent.vue
<template>
  <h1>Counter: {{ count }}</h1>
  <p>Double Count: {{ doubleCount }}</p>
  <button v-on:click="increment">Increment</button>
  <button v-on:click="decrement">Decrement</button>
</template>

<script>
export default {
  computed: {
    count() {
      return this.$store.state.count;
    },
    doubleCount() {
      return this.$store.getters.doubleCount;
    },
  },
  methods: {
    increment() {
      this.$store.commit("increment");
    },
    decrement() {
      this.$store.commit("decrement");
    },
  },
};
</script>

// 01_Studi/04_Front_End/09_Develop_Web_App_React.js/14_Redux_Extensions/05_Exercice_Defi/01_example_lesson/src/counter.jsx
import { useSelector, useDispatch } from 'react-redux'
import { increment, decrement } from './redux/counterSlice.js'

export default function Counter () {
  const count = useSelector(state => state.reducer.counter.value)
  const dispatch = useDispatch()
  return (
    <div>
      <span>{count}</span>
      <button onClick={() => dispatch(increment())}>
        Incrémenté le compteur
      </button>
      <button onClick={() => dispatch(decrement())}>Décrementé le compteur</button>
    </div>
  )
}
